openapi: 3.0.0
info:
  title: 5GSDigitalEntityNBI API
  description: NBI for 5GS Digital Entity
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /subscription/{ueID}:
    get:
      summary: get UE subscription information
      description: |
        get UE subscription information (SM-Data)
      operationId: getSubscriptionInfo
      parameters:
      - name: ueID
        in: path
        description: Unique ID of the UE
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Supi'
      responses:
        "200":
          description: The requested informations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionData'
        default:
          description: Generic-error
      x-swagger-router-controller: SubscriptionData
components:
  schemas:

    SubscriptionData:
      type: object
      properties:
        subscribedUeAmbr:
          $ref: '#/components/schemas/AmbrRm'
        nssai:
          $ref: '#/components/schemas/Nssai'

    Nssai:
      required:
      - defaultSingleNssais
      type: object
      properties:
        defaultSingleNssais:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/EnhancedSnssai'
        singleNssais:
          minItems: 0
          type: array
          items:
            $ref: '#/components/schemas/EnhancedSnssai'
      nullable: true

    EnhancedSnssai:
      required:
      - sst
      type: object
      properties:
        sst:
          maximum: 255
          minimum: 0
          type: integer
        sd:
          pattern: "^[A-Fa-f0-9]{6}$"
          type: string
        dnnConfigurations:
          description: A map (list of key-value pairs where Dnn, or optionally the Wildcard DNN, serves as key) of DnnConfigurations
          type: object
          additionalProperties:
             $ref: '#/components/schemas/DnnConfiguration'

    DnnConfiguration:
      required:
      - pduSessionTypes
      - sscModes
      type: object
      properties:
        pduSessionTypes:
          $ref: '#/components/schemas/PduSessionTypes'
        sscModes:
          $ref: '#/components/schemas/SscModes'
        "5gQosProfile":
          $ref: '#/components/schemas/SubscribedDefaultQos'
        sessionAmbr:
          $ref: '#/components/schemas/Ambr'
        staticIpAddress:
          maxItems: 2
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/IpAddress'

    IpAddress:
      type: object
      properties:
        ipv4Addr:
          $ref: '#/components/schemas/Ipv4Addr'
        ipv6Addr:
          $ref: '#/components/schemas/Ipv6Addr'
        ipv6Prefix:
          $ref: '#/components/schemas/Ipv6Prefix'
      oneOf:
      - required:
        - ipv4Addr
      - required:
        - ipv6Addr
      - required:
        - ipv6Prefix

    PduSessionTypes:
      required:
      - defaultSessionType
      type: object
      properties:
        defaultSessionType:
          $ref: '#/components/schemas/PduSessionType'
        allowedSessionTypes:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/PduSessionType'

    SscModes:
      required:
      - defaultSscMode
      type: object
      properties:
        defaultSscMode:
          $ref: '#/components/schemas/SscMode'
        allowedSscModes:
          maxItems: 3
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/SscMode'

    Supi:
      pattern: "^(imsi-[0-9]{5,15}|nai-.+|gci-.+|gli-.+|.+)$"
      type: string

    AmbrRm:
      anyOf:
      - $ref: '#/components/schemas/Ambr'
      - $ref: '#/components/schemas/NullValue'

    Ambr:
      required:
      - downlink
      - uplink
      type: object
      properties:
        uplink:
          $ref: '#/components/schemas/BitRate'
        downlink:
          $ref: '#/components/schemas/BitRate'

    BitRate:
      pattern: ^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$
      type: string

    NullValue:
      type: string
      enum:
      - null

    SubscribedDefaultQos:
      required:
      - 5qi
      - arp
      type: object
      properties:
        "5qi":
          $ref: '#/components/schemas/5Qi'
        arp:
          $ref: '#/components/schemas/Arp'
        priorityLevel:
          $ref: '#/components/schemas/5QiPriorityLevel'

    "5Qi":
      maximum: 255
      minimum: 0
      type: integer

    Arp:
      required:
      - preemptCap
      - preemptVuln
      - priorityLevel
      type: object
      properties:
        priorityLevel:
          $ref: '#/components/schemas/ArpPriorityLevel'
        preemptCap:
          $ref: '#/components/schemas/PreemptionCapability'
        preemptVuln:
          $ref: '#/components/schemas/PreemptionVulnerability'

    ArpPriorityLevel:
      maximum: 15
      minimum: 1
      type: integer
      description: nullable true shall not be used for this attribute

    PreemptionCapability:
      anyOf:
      - type: string
        enum:
        - NOT_PREEMPT
        - MAY_PREEMPT
      - type: string

    PreemptionVulnerability:
      anyOf:
      - type: string
        enum:
        - NOT_PREEMPTABLE
        - PREEMPTABLE
      - type: string

    "5QiPriorityLevel":
      maximum: 127
      minimum: 1
      type: integer

    Ipv4Addr:
      pattern: "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$"
      type: string

    Ipv6Addr:
      type: string
      allOf:
      - pattern: "^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))$"
      - pattern: "^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))$"

    Ipv6Prefix:
      type: string
      allOf:
      - pattern: "^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))(\\\
          /(([0-9])|([0-9]{2})|(1[0-1][0-9])|(12[0-8])))$"
      - pattern: "^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))(\\\
          /.+)$"

    PduSessionType:
      anyOf:
      - type: string
        enum:
        - IPV4
        - IPV6
        - IPV4V6
        - UNSTRUCTURED
        - ETHERNET
      - type: string

    SscMode:
      anyOf:
      - type: string
        enum:
        - SSC_MODE_1
        - SSC_MODE_2
        - SSC_MODE_3
      - type: string
